### PR TITLE
Replace Errno with dedicated Error types.

### PR DESCRIPTION
**Pull request by acook**
Errno is no longer a subclass of Exception in Crystal, instead it is an
Enum and becomes more of an implementation detail.

This set of changes doesn't go as far as it could for detecting the
Errno and making appropriate types, but it does get things compiling
again on the latest version of Crystal.

### CODE REVIEW

**Comment by acook** [comment]
I noticed some test failures, but I'm not sure if they have anything to do with my changes. Please double check.

**Comment by acook** [comment]
This is a PR? Is there a different branch or something that would work better for you?

**Comment by dscottboggs** [comment]
Sorry, I didn't see the PR, I just noticed that you had forked it and made the changes. I made that comment on the branch and github just stuck it here on the PR. Merging now, thanks again.

**Comment by acook** [comment]
Ah that makes sense. Thanks for making this binding!

**Pull request merged**
